### PR TITLE
Allow Developers to Access Product Type Resources

### LINKED ISSUE #5: Allow developers to access the Product Type resource
Verbs to be supported

- [x] GET
- [x] POST
- [x] PUT
- [x] DELETE

User should be able to GET a list, and GET a single item.

### PR DESCRIPTION
**Pull request by EliOJackson**
# Description

This is the API to Query Product Types. The following Verbs are supported:

- [x] GET one
- [x] GET all
- [x] POST
- [x] PUT
- [x] DELETE

To test these changes, you must first have your database created. Please run the following commands in the Root Directory to ensure that the DB has been created correctly:

$ npm install
$ touch .env
$ mkdir json
$ node db/build_data.js
$ node db/build_table.js
$ nodemon app.js

In the newly created .env file, please save the following, with XXXX being the four digit port that you wish to run:

PORT=XXXX
NODE_ENV="development"

________
Once you have taken these steps, ensure that nodemon is running and listening on the port that you provided above. In the following examples, the default PORT of 8080 will be used. You will now be able to make query calls using a testing tool such as Postman. 

Fixes #5 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

**GET**

Get all Product Types
- To get all product types, use the `GET` method in your API Testing application and query the following URL: 

```http://localhost:8080/api/v1/product_types```

Get one Product Type
- To get one product type, use the `GET` method in your API Testing application and query the following URL, replacing the ```<ID>``` with the id number of the product type you wish to query: 

```http://localhost:8080/api/v1/product_types/<ID>```

**POST**
- To add a product type, use the `POST` method in your API Testing application and query the following url while providing the new product type in JSON format. Please see the example below:

 ```http://localhost:8080/api/v1/product_types```

```
{
	"product_type_name": "what ever you'd like it to be"
}
```

**PUT**
- To update a product type, use the `PUT` method in your API Testing application and query the following url while replacing the ```<ID>``` with the id of the product type you wish to update. Then include the updated product name in your JSON post as seen below.

 ```http://localhost:8080/api/v1/product_types/<ID>```

```
{
        "product_type_name": "new name"
}
```

**DELETE**
- The delete query will only work on a product type  that does not have any corresponding products referencing its product type id. 
- To test, use the `DELETE` method in your API Testing application and query the following url,replacing ```<ID>``` with the product type id number that you wish to be deleted: 

```http://localhost:8080/api/v1/product_types/<ID>```

If the product type id does not have any corresponding products referencing it, the product type will be deleted from your database. Other wise, you will receive the following message:

```
{
    "message": "Error error error!",
    "error": "A Product Type may not be deleted if any Products using the Product Type's ID exist."
}
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by iiimosley — APPROVED** [review]
All tests/methods passing ☑️ 
Thank you for removing console.logs   
Party on, Wayne 🎸 🤘

**Review by iiimosley — APPROVED** [review]
approval still stands 👍

**Comment by CourtneyBrothers** [comment]
👍

**Review by sarahmorrisokeefe — APPROVED** [review]
💯

**Review by iiimosley — APPROVED** [review]
looking good bro!  (as stated IRL)

**Comment by spenceryork** [comment]
👍

**Pull request merged**
