### PR TITLE
Payment Type API access

### PR DESCRIPTION
**Pull request by spenceryork**
# Description

This pull request allows developers to access the Payment Type data in our database using the following API calls:

- GET
- POST
- PUT
- DELETE (user receives 405)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

In the project directory run the following commands:
1. node db/build_data.js
2. node db/build_table.js
3. run nodemon app.js in the project directory

**GET**
- Perform a GET API call to the following URL **http://localhost:<port_number>/api/v1/payment_types** to receive a JSON of all existing payment types
- Perform a GET API call to the following URL **http://localhost:<port_number>/api/v1/payment_types/2** to receive a JSON of one particular payment type.

**POST**
- To POST to the API make a POST API call to the aforementioned URL with the following JSON: 

```
{
 "customer_id": 32,
 "payment_option": "Moostercard",
 "account_number": 12345677998810
}
```

**PUT**
- To PUT to the API make a PUT API call to the aforementioned URL with the following JSON, which will update "Moostercard" from the previous POST to "Mastercard". Users will only be able to update payment_option and account_number: 
```
{
 "payment_option": "Mastercard",
 "account_number": 12345677998810
}
```

**DELETE**
- As a group we decided it would not be logical to allow a payment type to be deleted since payment types are only created once an order has been payed for, and therefore the payment type data is necessary to keep.
- When a user sends any payment type DELETE call to the API they will receive the following error message:
```
{"message":"Error error error!","error":"You are not authorized to delete an existing payment type"}
```

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by CourtneyBrothers** [comment]
looks good!

id recommend you change the PR request to use variables in place of  localhost:8080 path and the get example get one of a particular type to a variable request as well 
1)payment_id does not need to be in the example object for the post method because your payment id is being auto-incremented

**Review by CourtneyBrothers — CHANGES_REQUESTED** [review]
looks good!

id recommend you change the PR request to use variables in place of localhost:8080 path and the get example get one of a particular type to a variable request as well
1)payment_id does not need to be in the example object for the post method because your payment id is being auto-incremented

**Comment by spenceryork** [comment]
@CourtneyBrothers - No problem. Both changes to the PR text are complete.

**Review by iiimosley — COMMENTED** [review]
Something we all might need to talk about on Monday with our data structure:
- With `POST`, should we only update `account_number` & `payment_option` as to not manipulate data tied to `orders` where both `orders.customer_id` & `customers.customer_id` have a corresponding `payment_type`?

**Comment by spenceryork** [comment]
@courtney & @iiimosley - The requested changes have been made and pushed up. You should now be able to review the changes made.

**Comment by spenceryork** [comment]
@iiimosley DELETE has been updated on PR and README. Merge conflicts with Courtney's branch have been resolved.

**Review by EliOJackson — APPROVED** [review]
Able to complete all queries, code looks fresh, 🇺🇸

**Review by CourtneyBrothers — APPROVED** [review]

**Pull request merged**
