### PR TITLE
Allow Developers to Access Computer Resource

### LINKED ISSUE #8: Allow developers to access the Computer resource
Verbs to be supported

- [x] GET all
- [x] GET one
- [x] POST
- [x] PUT
- [x] DELETE

User should be able to GET a list, and GET a single item.

### PR DESCRIPTION
**Pull request by sarahmorrisokeefe**
# Description

This pull request allows the developer to access the Computer data in our database using GET, POST, PUT, and DELETE methods. The developer is able to GET all orders and GET single computers, POST a new computer (with just a purchase date and not a decommission date), PUT a different value for an existing computer (I.E. adding a decommission date where it is currently null), and DELETE will only throw a specific error, because the user is not allowed to delete a computer. 

This pull request requires that you already have the database created. Please do the following:
1. `~ npm install`
2. Create a `.env` file that matches the `.env.example` file, with your specified PORT number. We used PORT 8080, so that's what it is in the examples.
3. `~ mkdir json`
4. `node db/build_data.js`
5. `node db/build_table.js`
6. `nodemon app.js`

The final step should start your server on the port you selected. You are now ready to test the API calls using an app like Postman.

Fixes #8 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**GET**
- To get all computers, go to: **http://localhost:8080/api/v1/computers/** - this should return a JSON file of all existing computers, both active and decommissioned
- To get one single computer, go to: **http://localhost:8080/api/v1/computers/<COMPUTER ID NUMBER>** - you need to insert the `computer_id` number you're looking to get at the end of the URL, and it should return a JSON file of just one order with that specific order ID

**POST**
- To add a computer, use the `POST` method and go to: **http://localhost:8080/api/v1/computers with the order that you want to add in JSON format. Here is my example:
```
{
	"purchase_date":"2010-01-01"
}
```
- If you refresh the data, you should see a new line with an automatically generated `computer_id`, the new `purchase_date` of 2010-01-01, and the 'decommission_date' will automatically be 'NULL'

**PUT**
- To edit a current computer, use the `PUT` method and go to **http://localhost:8080/api/v1/computers/<COMPUTER ID NUMBER>** and add the `computer_id` you want to edit the content for. Here is my example:
```
http://localhost:8080/api/v1/computers/1

{
	"decommission_date":"2010-02-01"
}
```
- This will update the data so that the order with an `computer_id` of 1, will have a `decommission_date` of 2010-02-01
- NOTE: if you edit a `computer_id` that is currently assigned to an employee on the `employee_computer` join table, the `decommission_date` will be edited there to match your new `decommission_date` from the PUT method

**DELETE**
- The delete method is not available, as the user is not allowed to delete a computer from the database. If the user tries to delete a computer, he or she will get an error message such as this: 
```
{
    "message": "Error error error!",
    "error": "You cannot delete a computer from the system. Please use the PUT method to add a decommission date."
}
```

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [n/a] I have added tests that prove my fix is effective or that my feature works
- [n/a] New and existing unit tests pass locally with my changes
- [n/a] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by sarahmorrisokeefe** [comment]
Also note - I didn't add anything to the readme because it seems like we're going to edit all of that anyways

**Review by iiimosley — APPROVED** [review]
Rock 'n Roll 🤘

**Review by spenceryork — COMMENTED** [review]
👍 👍

**Comment by CourtneyBrothers** [comment]
send it

**Pull request merged**
