### PR TITLE
Tj-Setup

### PR DESCRIPTION
**Pull request by EliOJackson**
# Initial file structure set up for our first sprint, including our initial customers and employees tables being built. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?
This has been tested using the command line to create our data and then build the table. Using DB Browser for SQLite, I was able to confirm that the data and table had been updated successfully.

**Provide instructions so we can reproduce.** 

To test this process, on your command line, first run **node db/build_data.js**. This will produce the json file in your json folder. Then run **node db/build_table.js**, which will produce the .sqlite file in your root directory.

Once you have created the json files and the .sqlite file, open your DB Browser for SQLite Application. Select Open Data base at the top of the application, and find your project directory. Select the .sqlite file and open it to browse the data. 

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by CourtneyBrothers** [comment]
gitignore json data make w/ faker

**Comment by CourtneyBrothers** [comment]
remove customers.js file

**Comment by CourtneyBrothers** [comment]
👍

**Review by iiimosley — APPROVED** [review]
🔥🌯🔥

**Review by sarahmorrisokeefe — APPROVED** [review]
👍

**Comment by spenceryork** [comment]
👍

**Comment by sarahmorrisokeefe** [comment]
TO RUN: 

1. `npm install`
2. Create 'json' folder in root
3. `node db/build_data.js`
4. `node db/build_table.js`

**Pull request merged**
