### PR TITLE
API Query for Customers with No Order Activity

### PR DESCRIPTION
**Pull request by iiimosley**
# Description

By using the URL parameter `/customers/?active=false`, the JSON response should only contain customers that don't have any orders placed yet.

Please reload the database by running the following commands in the root directory
```
$ npm install
$ touch .env
$ mkdir json
$ node db/build_data.js
$ node db/build_table.js
$ nodemon app.js
```
Enter the following into the newly created `.env` file:
```
PORT=<desired 4-digit port number>
NODE_ENV="DEVELOPMENT"
```

__Ticket Completed:__ #11 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## Testing

Please run the following query with a `GET` command in your preferred API testing tool (e.g., Postman) or in your browser with JSON Viewer enabled:
```
http://localhost:<definied port number>/api/v1/customers/?active=false
```

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by EliOJackson — APPROVED** [review]
I was able to follow the steps and replicate the appropriate data using Postman. Comments on the code were helpful as well. 👍

**Review by sarahmorrisokeefe — APPROVED** [review]
Ballin 🏀

**Comment by CourtneyBrothers** [comment]
👍

**Comment by sarahmorrisokeefe** [comment]
Still looks 'ballin' ⚾️

**Comment by spenceryork** [comment]
💯

**Pull request merged**
