### PR TITLE
API to Query Products

### LINKED ISSUE #2: Allow developers to access Product resource
Verbs to be supported

- [x] GET one
- [x] GET all
- [x] POST
- [x] PUT
- [x] DELETE

User should be able to GET a list of products, and GET a single product.

### PR DESCRIPTION
**Pull request by iiimosley**
# Description

Product Table verbs to be supported
- [x] GET one
- [x] GET all
- [x] POST
- [x] PUT
- [x] DELETE

Please reload the database by running the following commands in the root directory
```
$ npm install
$ touch .env
$ mkdir json
$ node db/build_data.js
$ node db/build_table.js
$ nodemon app.js
```
Enter the following into the newly created `.env` file:
```
PORT=<desired 4-digit port number>
NODE_ENV="DEVELOPMENT"
```

Fixes #2 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

**GET**
Please run the following query with a `GET` command to receive all products from the `products` table in your preferred API testing tool (e.g., Postman) or in your browser with JSON Viewer enabled:
```
http://localhost:<definied port number>/api/v1/product
```

To `GET` an individual product, please run the following query with the `product_id` inserted into the route parameters
```
http://localhost:<definied port number>/api/v1/product/<product id integer>
``` 

**POST**
To add a product to the `products` table using your API testing tool, use `POST` method to the following query with your JSON formatted as such
```
http://localhost:<port#>/api/v1/product

{
	"product_name": "automatic blinker fluid",
	"product_type": 3,
	"price": 45666,
	"description": "for when your car blinker just doesnt wanna blink any longer",
	"customer_id": 21,
	"listing_date": "2012-03-03"
}
```

**PUT**
Using the same JSON formatting as before, use the `PUT` method to update/overwrite a specific `product` row by passing the `product_id` into the route parameters: 
```
http://localhost:8080/api/v1/orders/<product_id>
```

**DELETE**
`DELETE` method on the `products` table will only work if the specified `product_id` is not found on any row with `order_products` table. 

If the `product_id` matches to any row on `order_products` by running the following query, the proceeding message will be sent back:
```
http://localhost:8080/api/v1/product/<product_id>
{
    "message": "Error error error!",
    "error": "This product can not be deleted""
}
```

If the `product_id` does not match to any row on `order_products` by running the query, an empty JSON will be returned. Please check your database to ensure the specified `product_id` is no longer on the `products` table.

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by EliOJackson — CHANGES_REQUESTED** [review]
Hey Trey, in your PR on the Post example, your JSON example needs to be updated. Currently, the properties are in camel case, while it needs to be in snake case. 

ex:

``` 
{
	"product_name": "automatic blinker fluid",
	"product_type": 3,
	"price": 45666,
	"description": "for when your car blinker just doesnt wanna blink any longer",
	"customer_id": 21,
	"listing_date": "2012-03-03"
}

**Comment by iiimosley** [comment]
@EliOJackson Good eye, thanks for pointing that out. Changes to documentation have been made

**Review by EliOJackson — APPROVED** [review]

**Review by EliOJackson — APPROVED** [review]
TY for updating. All verbs are working correctly, code is clean and well commented. 🅰️ ➕

**Review by sarahmorrisokeefe — APPROVED** [review]
Still looks good :octocat:

**Comment by CourtneyBrothers** [comment]
totes sauce

**Pull request merged**
