### PR TITLE
Cb dep

### LINKED ISSUE #7: Allow developers to access the Department resource
Verbs to be supported

1. GET
1. POST
1. PUT

User should be able to GET a list, and GET a single item.

### PR DESCRIPTION
**Pull request by CourtneyBrothers**
# Description

allow employers to access department Resource
verbs supported
GET
POST
PUT

Fixes #7 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# How Has This Been Tested?

#department resource access 
1) run 
`nodemon app.js` in project directory  

2) to getAllDepartments visit http://localhost:<_your_port number>/api/v1/departments
this should serve the customers JSON 

3) to getOneDepartment visit http://localhost:<_your_port number>/api/v1/departments/_department_id_

4)postOneDepartment

recommended to use postman to pass department object 

example: 

{
"departmentName": "CARS",
"supervisorId": 1,
"budget": 14888
}

department object will add the department object at the _department_id_ at the next position

5) putOneDepartment

PUT:localhost:<_your_port_number>/api/v1/departments/_department_id_

department object will replace the department object at the _department_id_ position specified in the http request 

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by EliOJackson — APPROVED** [review]
👍  Looks good, just make sure to fix Readme conflicts first =)

**Review by EliOJackson — APPROVED** [review]
my Approval Still Stands

**Review by sarahmorrisokeefe — APPROVED** [review]
Looks good 🌸

**Review by iiimosley — APPROVED** [review]
🎆 ⛳️ 🏌️

**Pull request merged**
